run:
  deadline: 15m
  issues-exit-code: 1
issues:
  max-same-issues: 0
linters:
  disable-all: true
  enable:
  - goconst
  - gosec
  - gosimple
  - ineffassign
  - lll
  - misspell
  - staticcheck
  - unconvert
  - govet
  - unused
linters-settings:
  gosec:
    excludes:
      - "G101" # Potential hardcoded credentials
      - "G505" # Allow usage of SHA1
  staticcheck:
    go: "1.19"
    checks:
      - "all"
      - "-SA1029" # Inappropriate key in call to context.WithValue
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
